version: '3.8'

services:
  flask-app:
    image: your-flask-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE=postgres
      - USER=postgres
      - HOST=db
      - PASSWORD=yourpassword
      - PORT=5432
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge